### ISSUE TITLE
Need better documentation of how to connect external transcoders to the load balancer

### ISSUE THREAD

**Issue by Snipey** [UnicornTranscoder/UnicornLoadBalancer#24]
I have searched the web and have not found much about how to set this project up.

I have managed to get the loadbalancer running and the Plex server to the latest supported version `1.18.1944` every combination of ip adresses and cloudflare urls would not fix the `s1001 Network` Error

```
  loadbalancer:
    image: magn2o/unicorn-loadbalancer:latest
    depends_on:
      - plex
      - redis
    networks:
      - plex-network
    ports:
      - "3001:3001/tcp"
    environment:
      - PUID=0
      - PGID=0
      - SERVER_HOST=loadbalancer
      - SERVER_PORT=3001
      - SERVER_PUBLIC=https://plex.domain.com/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PLEX_HOST=plex
      - PLEX_PORT=32400
      - PLEX_PATH_SESSIONS=/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions
      - DATABASE_SQLITE_PATH=/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db
      - LB_URL=http://loadbalancer:3001/
      - CUSTOM_IMAGE_PROXY=https://images.weserv.nl/
      - CUSTOM_SERVERS_LIST=['https://transcode-1.domain.com']
```

```
  transcoder-1:
    hostname: transcoder-1
    image: magn2o/unicorn-transcoder
    networks:
      - plex-network
    ports:
      - '3000:32400/tcp'
    environment:
      - 'SERVER_PORT=32400'
      - 'LOADBALANCER_IP=https://plex.domain.com'
      - 'INSTANCE_ADDRESS=https://transcode-1.domain.com'
      - 'PLEX_TOKEN=<TOKENHERE>'
```
