### ISSUE TITLE
Unsure of Variable `PLEX_PATH_USR` when using Docker

### ISSUE THREAD

**Issue by kennyparsons** [UnicornTranscoder/UnicornLoadBalancer#38]
I use plex in a docker (linuxserver). The path `/usr/lib/plexmediaserver` is not exposed to the host. So i'm not sure what value to use. 
PLEX_PATH_USR | The Plex's path | string | /usr/lib/plexmediaserver/
-- | -- | -- | --

**Comment by davidjameshowell** [comment]
@kennyparsons - You should (ideally) run the load balancer on the same host as your Plex installation. On Docker, you simply pass in the PMS config volume or host mount (where your Plex data resides).

For examaple:
```
plex:
  image: lsio:plex
  volume:
    - plex_data:/config

unicorn-loadbalancer:
  image: unicorn-loadbalancer
  volumes:
      - plex_data:/plex_config
  environment:
    - PLEX_PATH_USR=/plex_config
```

Hopefully this helps some!
